// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System_ApiTest.Infrastructure.Persistence;

#nullable disable

namespace System_ApiTest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812185752_AddEventDetailsMotifAndResourceAllocation")]
    partial class AddEventDetailsMotifAndResourceAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("[Role] = 'Owner'");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotifiedCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Auditlog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BookingName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BrideName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CancellationRequestReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CelebrantAge")
                        .HasColumnType("int");

                    b.Property<string>("CelebrantName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CelebrantSex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepositStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GroomName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("MenuPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motif")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotifImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Theme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThemeImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventDate");

                    b.HasIndex("MenuPackageId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_EndAfterStart", "[EndDate] IS NULL OR ([EndDate] > [EventDate]) OR ([EndDate] = [EventDate] AND [EndTime] > [StartTime])");

                            t.HasCheckConstraint("CK_Booking_EndDateNotBefore", "[EndDate] IS NULL OR [EndDate] >= [EventDate]");

                            t.HasCheckConstraint("CK_Booking_GuestCountPositive", "[GuestCount] IS NULL OR [GuestCount] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingMenuItem", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CapturedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BookingMenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_BookingMenuItem_QtyPositive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingMenuTray", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CapturedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "TrayId");

                    b.HasIndex("TrayId");

                    b.ToTable("BookingMenuTrays", t =>
                        {
                            t.HasCheckConstraint("CK_BookingMenuTray_QtyPositive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingResourceAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Chairs")
                        .HasColumnType("int");

                    b.Property<int>("Forks")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("LongTables")
                        .HasColumnType("int");

                    b.Property<int>("Others")
                        .HasColumnType("int");

                    b.Property<int>("Plates")
                        .HasColumnType("int");

                    b.Property<int>("RoundTables")
                        .HasColumnType("int");

                    b.Property<int>("Servers")
                        .HasColumnType("int");

                    b.Property<int>("Spoons")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Waiters")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("BookingResourceAllocations", t =>
                        {
                            t.HasCheckConstraint("CK_BookingResourceAllocation_CountsInRange", "[LongTables] BETWEEN 0 AND 100000 AND [RoundTables] BETWEEN 0 AND 100000 AND [Chairs] BETWEEN 0 AND 100000 AND [Plates] BETWEEN 0 AND 100000 AND [Spoons] BETWEEN 0 AND 100000 AND [Forks] BETWEEN 0 AND 100000 AND [Waiters] BETWEEN 0 AND 100000 AND [Servers] BETWEEN 0 AND 100000 AND [Others] BETWEEN 0 AND 100000");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Bookinghistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("BookingId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("BookingHistories");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Bookingpackageselection", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuPackageSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId", "MenuPackageSlotId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("MenuPackageSlotId");

                    b.ToTable("BookingPackageSelections");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Calendarday", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ConfirmedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsManuallyLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Date");

                    b.ToTable("CalendarDays", t =>
                        {
                            t.HasCheckConstraint("CK_CalendarDay_ConfirmedCountNonNeg", "[ConfirmedCount] >= 0");

                            t.HasCheckConstraint("CK_CalendarDay_MaxCapacityPositive", "[MaxCapacity] >= 1");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Conversationmessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToolPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FoodTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RentalTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_DueOnOrAfterIssue", "[DueDate] >= [IssueDate]");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.MenuTrayDish", b =>
                {
                    b.Property<Guid>("MenuTrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuTrayId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuTrayDishes");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menuitem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("MenuPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PricePerTray")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServesPerTray")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemName")
                        .IsUnique();

                    b.HasIndex("MenuPackageId");

                    b.ToTable("MenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_MenuItem_PricedIfStandalone", "([MenuPackageId] IS NOT NULL) OR ([PricePerTray] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MenuItem_ServesPositive", "[ServesPerTray] >= 1");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPax")
                        .HasColumnType("int");

                    b.Property<int>("MinPax")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerExtraPax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuPackages", t =>
                        {
                            t.HasCheckConstraint("CK_MenuPackage_BasePriceNonNeg", "[BasePrice] >= 0");

                            t.HasCheckConstraint("CK_MenuPackage_ExtraPaxNonNeg", "[PricePerExtraPax] >= 0");

                            t.HasCheckConstraint("CK_MenuPackage_MaxPaxGteMin", "[MaxPax] >= [MinPax]");

                            t.HasCheckConstraint("CK_MenuPackage_MinPaxPositive", "[MinPax] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackagefixeditem", b =>
                {
                    b.Property<Guid>("MenuPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuPackageId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuPackageFixedItems");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackageslot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChooseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MenuPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuPackageId");

                    b.ToTable("MenuPackageSlots", t =>
                        {
                            t.HasCheckConstraint("CK_MenuPackageSlot_ChooseCountPositive", "[ChooseCount] >= 1");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menutray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PricePerTray")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServesMax")
                        .HasColumnType("int");

                    b.Property<int>("ServesMin")
                        .HasColumnType("int");

                    b.Property<string>("TrayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MenuTrays", t =>
                        {
                            t.HasCheckConstraint("CK_MenuTray_PriceNonNeg", "[PricePerTray] >= 0");

                            t.HasCheckConstraint("CK_MenuTray_ServesMaxGteMin", "[ServesMax] >= [ServesMin]");

                            t.HasCheckConstraint("CK_MenuTray_ServesMinPositive", "[ServesMin] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserType", "UserId", "Purpose", "ConsumedAt");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GatewayPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayProvider")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GatewaySessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayStatusRaw")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundRequestDecision")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefundRequestReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RefundRequested")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RefundRequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RefundedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GatewaySessionId")
                        .HasFilter("[GatewaySessionId] IS NOT NULL");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasFilter("[TransactionReference] IS NOT NULL AND [Status] <> 'Failed'");

                    b.HasIndex("TransactionReference", "Status");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_AmountPositive", "[AmountPaid] > 0");

                            t.HasCheckConstraint("CK_Payment_RefundWithinPaid", "[RefundedAmount] >= 0 AND [RefundedAmount] <= [AmountPaid]");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DamageNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RentalItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RentalItemId");

                    b.ToTable("Rentals", t =>
                        {
                            t.HasCheckConstraint("CK_Rental_QuantityPositive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Rentalitem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RentalItems", t =>
                        {
                            t.HasCheckConstraint("CK_RentalItem_TotalQtyPositive", "[TotalQuantity] > 0");

                            t.HasCheckConstraint("CK_RentalItem_UnitPriceNonNeg", "[UnitPrice] >= 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Revokedtoken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Sentnotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("BookingId", "Kind", "Period")
                        .IsUnique();

                    b.ToTable("SentNotifications");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("Services", t =>
                        {
                            t.HasCheckConstraint("CK_Service_QuantityPositive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Serviceitem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiceItems", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceItem_UnitCostNonNeg", "[UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.SlotCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("MenuPackageSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuPackageSlotId");

                    b.ToTable("SlotCategories", t =>
                        {
                            t.HasCheckConstraint("CK_SlotCategory_AtLeastOne", "[ItemCategory] IS NOT NULL OR [CourseCategory] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Supportmessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttachmentFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadByAdminAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadByCustomerAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CreatedAt");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Supportthread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("SupportThreads");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Systemsettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChairsPerGuest")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DefaultMaxCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("DepositPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("EventBufferHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("GuestsPerLongTable")
                        .HasColumnType("int");

                    b.Property<int>("GuestsPerRoundTable")
                        .HasColumnType("int");

                    b.Property<int>("GuestsPerServer")
                        .HasColumnType("int");

                    b.Property<int>("GuestsPerWaiter")
                        .HasColumnType("int");

                    b.Property<int>("MinLeadDaysDelivery")
                        .HasColumnType("int");

                    b.Property<int>("MinLeadDaysFullService")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OperatingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OperatingHoursStart")
                        .HasColumnType("time");

                    b.Property<int>("RentalTurnaroundDays")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SingletonGuard")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("UtensilsPerGuest")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("SingletonGuard")
                        .IsUnique();

                    b.ToTable("SystemSettings", t =>
                        {
                            t.HasCheckConstraint("CK_SystemSettings_BufferNonNeg", "[EventBufferHours] >= 0");

                            t.HasCheckConstraint("CK_SystemSettings_DefaultCapacity", "[DefaultMaxCapacity] >= 1");

                            t.HasCheckConstraint("CK_SystemSettings_DepositPctRange", "[DepositPercentage] >= 0 AND [DepositPercentage] <= 1");

                            t.HasCheckConstraint("CK_SystemSettings_LeadDaysNonNeg", "[MinLeadDaysFullService] >= 0 AND [MinLeadDaysDelivery] >= 0");

                            t.HasCheckConstraint("CK_SystemSettings_OperatingHoursOrder", "[OperatingHoursEnd] > [OperatingHoursStart]");

                            t.HasCheckConstraint("CK_SystemSettings_ReservationFeeNonNeg", "[ReservationFee] >= 0");

                            t.HasCheckConstraint("CK_SystemSettings_SuggestDivisorsPositive", "[GuestsPerLongTable] >= 1 AND [GuestsPerRoundTable] >= 1 AND [GuestsPerWaiter] >= 1 AND [GuestsPerServer] >= 1");

                            t.HasCheckConstraint("CK_SystemSettings_SuggestMultipliersNonNeg", "[ChairsPerGuest] >= 0 AND [UtensilsPerGuest] >= 0");

                            t.HasCheckConstraint("CK_SystemSettings_TaxRateNonNeg", "[TaxRate] >= 0");

                            t.HasCheckConstraint("CK_SystemSettings_TurnaroundNonNeg", "[RentalTurnaroundDays] >= 0");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeratedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModeratedById");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("Testimonials", t =>
                        {
                            t.HasCheckConstraint("CK_Testimonial_RatingRange", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Admin", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Admin", "CreatedBy")
                        .WithMany("CreatedAssistants")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Admin", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Auditlog", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Booking", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Calendarday", "CalendarDay")
                        .WithMany("Bookings")
                        .HasForeignKey("EventDate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menupackage", "MenuPackage")
                        .WithMany()
                        .HasForeignKey("MenuPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CalendarDay");

                    b.Navigation("Customer");

                    b.Navigation("MenuPackage");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingMenuItem", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("MenuItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menuitem", "Item")
                        .WithMany("BookingMenuItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingMenuTray", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("MenuTrays")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menutray", "Tray")
                        .WithMany("BookingMenuTrays")
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.BookingResourceAllocation", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithOne("ResourceAllocation")
                        .HasForeignKey("System_ApiTest.Domain.Entities.BookingResourceAllocation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Bookinghistory", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("History")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Admin", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Bookingpackageselection", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("PackageSelections")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menuitem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menupackageslot", "Slot")
                        .WithMany("Selections")
                        .HasForeignKey("MenuPackageSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("MenuItem");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Conversationmessage", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("System_ApiTest.Domain.Entities.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.MenuTrayDish", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Menuitem", "MenuItem")
                        .WithMany("TrayDishes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menutray", "MenuTray")
                        .WithMany("Dishes")
                        .HasForeignKey("MenuTrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("MenuTray");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menuitem", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Menupackage", "MenuPackage")
                        .WithMany("Items")
                        .HasForeignKey("MenuPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MenuPackage");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackagefixeditem", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Menuitem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Menupackage", "MenuPackage")
                        .WithMany("FixedItems")
                        .HasForeignKey("MenuPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("MenuPackage");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackageslot", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Menupackage", "MenuPackage")
                        .WithMany("Slots")
                        .HasForeignKey("MenuPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuPackage");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Payment", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Rental", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("Rentals")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Rentalitem", "RentalItem")
                        .WithMany("Rentals")
                        .HasForeignKey("RentalItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("RentalItem");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Sentnotification", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("System_ApiTest.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Service", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany("Services")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Serviceitem", "ServiceItem")
                        .WithMany("Services")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.SlotCategory", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Menupackageslot", "Slot")
                        .WithMany("AllowedCategories")
                        .HasForeignKey("MenuPackageSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Supportmessage", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Supportthread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Supportthread", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Testimonial", b =>
                {
                    b.HasOne("System_ApiTest.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System_ApiTest.Domain.Entities.Admin", "ModeratedBy")
                        .WithMany()
                        .HasForeignKey("ModeratedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("ModeratedBy");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Admin", b =>
                {
                    b.Navigation("CreatedAssistants");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Booking", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Invoice");

                    b.Navigation("MenuItems");

                    b.Navigation("MenuTrays");

                    b.Navigation("PackageSelections");

                    b.Navigation("Rentals");

                    b.Navigation("ResourceAllocation");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Calendarday", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menuitem", b =>
                {
                    b.Navigation("BookingMenuItems");

                    b.Navigation("TrayDishes");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackage", b =>
                {
                    b.Navigation("FixedItems");

                    b.Navigation("Items");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menupackageslot", b =>
                {
                    b.Navigation("AllowedCategories");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Menutray", b =>
                {
                    b.Navigation("BookingMenuTrays");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Rentalitem", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Serviceitem", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("System_ApiTest.Domain.Entities.Supportthread", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}


